"use strict";
(()=>{
  const byId=id=>document.getElementById(id);
  const node=(tag,text,className="")=>{const item=document.createElement(tag);item.textContent=text;if(className)item.className=className;return item};
  const dateKey=date=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Stockholm",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
  const monday=date=>{const copy=new Date(date);copy.setDate(copy.getDate()-((copy.getDay()+6)%7));return dateKey(copy)};
  let loaded=false,selectedWeek=monday(new Date());
  function changeWeek(days){const next=new Date(selectedWeek+"T12:00:00");next.setDate(next.getDate()+days);selectedWeek=dateKey(next);load(byId("calendar-contact").value)}
  function formatWeek(start){const first=new Date(start+"T12:00:00"),last=new Date(first);last.setDate(last.getDate()+4);const format=new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric",timeZone:"Europe/Stockholm"});return first.getMonth()===last.getMonth()?format.format(first):`${format.format(first)} – ${format.format(last)}`}
  function focusEvent(current,delta){const events=[...byId("calendar-grid").querySelectorAll(".calendar-event")];const index=events.indexOf(current);if(index>=0)events[(index+delta+events.length)%events.length].focus()}
  function eventKey(event){if(event.key==="ArrowRight"||event.key==="ArrowDown"){event.preventDefault();focusEvent(event.currentTarget,1)}if(event.key==="ArrowLeft"||event.key==="ArrowUp"){event.preventDefault();focusEvent(event.currentTarget,-1)}}
  function render(data){
    const grid=byId("calendar-grid"),agenda=byId("calendar-agenda"),empty=byId("calendar-empty");grid.replaceChildren();agenda.replaceChildren();
    if(!data.week_start){grid.hidden=true;agenda.hidden=true;empty.hidden=false;byId("calendar-week-label").textContent="Select a contact";return}
    empty.hidden=true;grid.hidden=false;agenda.hidden=false;byId("calendar-week-label").textContent=formatWeek(data.week_start);grid.append(node("div",data.timezone,"calendar-timezone"));
    const days=[];for(let index=0;index<5;index++){const day=new Date(data.week_start+"T12:00:00");day.setDate(day.getDate()+index);days.push(day);const header=node("div","","calendar-day-header");header.setAttribute("role","columnheader");header.append(node("span",new Intl.DateTimeFormat("en-GB",{weekday:"short",timeZone:data.timezone}).format(day)),node("strong",String(day.getDate())));if(dateKey(day)===dateKey(new Date()))header.classList.add("is-today");grid.append(header)}
    const matches=(item,day,time)=>dateKey(new Date(item.starts_at))===dateKey(day)&&new Intl.DateTimeFormat("sv-SE",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:data.timezone}).format(new Date(item.starts_at))===time;
    ["09:00","13:30"].forEach(time=>{grid.append(node("div",time,"calendar-time"));days.forEach(day=>{const cell=node("div","","calendar-cell");cell.setAttribute("role","gridcell");const booking=data.booked_events.find(item=>matches(item,day,time)),slot=data.available_slots.find(item=>matches(item,day,time));if(booking){const event=node("button",`${time}\nBooked · ${booking.meeting_topic}\n${booking.request_id}`,"calendar-event is-booked");event.type="button";event.setAttribute("aria-label",`${new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:data.timezone}).format(new Date(booking.starts_at))} at ${time}, confirmed demo booking, ${booking.meeting_topic}`);event.addEventListener("keydown",eventKey);cell.append(event)}else if(slot){const event=node("button",`${time}\nAvailable`,`calendar-event`);event.type="button";event.setAttribute("aria-label",`${new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:data.timezone}).format(new Date(slot.starts_at))} at ${time}, simulated availability`);event.addEventListener("keydown",eventKey);cell.append(event)}grid.append(cell)})});
    days.forEach(day=>{const section=node("section","","calendar-agenda-day");section.append(node("h4",new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",timeZone:data.timezone}).format(day)));data.booked_events.filter(item=>dateKey(new Date(item.starts_at))===dateKey(day)).forEach(item=>section.append(node("div",`${new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:data.timezone}).format(new Date(item.starts_at))} · Booked · ${item.meeting_topic} · ${item.request_id}`,"calendar-agenda-event is-booked")));data.available_slots.filter(slot=>dateKey(new Date(slot.starts_at))===dateKey(day)).forEach(slot=>section.append(node("div",`${new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:data.timezone}).format(new Date(slot.starts_at))} · Available`,"calendar-agenda-event")));agenda.append(section)});
  }
  async function load(contactId=""){
    const button=byId("calendar-refresh"),status=byId("calendar-status"),select=byId("calendar-contact");button.disabled=true;status.textContent="Loading simulated calendar…";
    try{const query=contactId?`?contact_id=${encodeURIComponent(contactId)}&week_start=${encodeURIComponent(selectedWeek)}`:"";const data=await api("calendar"+query);if(!loaded){select.replaceChildren(node("option","Select an approved contact"));select.firstChild.value="";data.contacts.forEach(contact=>{const option=node("option",`${contact.name} · ${contact.job_title} · ${contact.company}`);option.value=contact.contact_id;select.append(option)});loaded=true}const booked=data.booked_events.length;status.textContent=`${data.provider_label} · ${data.timezone} · ${data.duration_minutes} minutes · ${booked} confirmed demo booking${booked===1?"":"s"} · No external calendar or real invitations.`;render(data)}catch(problem){status.textContent="Simulated calendar unavailable: "+problem.message}finally{button.disabled=false}
  }
  byId("calendar-refresh").addEventListener("click",()=>load(byId("calendar-contact").value));byId("calendar-contact").addEventListener("change",event=>load(event.target.value));byId("calendar-today").addEventListener("click",()=>{selectedWeek=monday(new Date());load(byId("calendar-contact").value)});byId("calendar-previous").addEventListener("click",()=>changeWeek(-7));byId("calendar-next").addEventListener("click",()=>changeWeek(7));document.querySelector('[data-tab="calendar"]').addEventListener("click",()=>{if(!loaded)load()});
})();
