"use strict";
(()=>{
  const byId=id=>document.getElementById(id),node=(tag,text,className="")=>{const item=document.createElement(tag);item.textContent=text;if(className)item.className=className;return item};
  let state=null,editing=null,loaded=false;
  function rulePayload(){return{rule_id:byId("regex-id").value,name:byId("regex-name").value,intent:byId("regex-intent").value,pattern:byId("regex-pattern").value,priority:Number(byId("regex-priority").value),language:byId("regex-language").value,enabled:byId("regex-enabled").checked}}
  function openEditor(rule=null){editing=rule?.rule_id||null;byId("regex-editor-title").textContent=rule?"Edit rule":"Add rule";byId("regex-id").value=rule?.rule_id||"";byId("regex-id").readOnly=Boolean(rule);byId("regex-name").value=rule?.name||"";byId("regex-intent").value=rule?.intent||"PRODUCT_INFORMATION";byId("regex-pattern").value=rule?.pattern||"";byId("regex-priority").value=rule?.priority||100;byId("regex-language").value=rule?.language||"all";byId("regex-enabled").checked=rule?.enabled??true;byId("regex-confirm").checked=false;byId("regex-editor").hidden=false;byId("regex-id").focus()}
  function render(data){state=data;byId("regex-status").textContent=`${data.rules.length} routing rules · revision ${data.revision} · protected security expressions are not editable.`;const results=byId("regex-results");results.replaceChildren();data.rules.forEach(rule=>{const card=node("article","","regex-rule"+(rule.enabled?"":" is-disabled"));card.append(node("h3",rule.name),node("p",`${rule.intent} · Priority ${rule.priority} · ${rule.language==="all"?"All languages":rule.language.toUpperCase()} · ${rule.enabled?"Enabled":"Disabled"}`,"regex-meta"),node("code",rule.pattern,"regex-pattern"));const actions=node("div","","regex-actions"),edit=node("button","Edit","secondary"),toggle=node("button",rule.enabled?"Disable":"Enable","secondary"),remove=node("button","Delete","regex-delete");edit.type=toggle.type=remove.type="button";edit.addEventListener("click",()=>openEditor(rule));toggle.addEventListener("click",()=>change("update",{...rule,enabled:!rule.enabled},`change ${rule.rule_id}`));remove.addEventListener("click",()=>change("delete",rule,`delete ${rule.rule_id}`));actions.append(edit,toggle,remove);card.append(actions);results.append(card)})}
  async function load(){byId("regex-status").textContent="Loading routing rules…";try{render(await api("regex"));loaded=true;document.querySelectorAll("#regex fieldset").forEach(item=>item.disabled=false)}catch(problem){byId("regex-status").textContent=problem.message}}
  async function change(operation,rule,label){if(!confirm(`Confirm ${label}? This changes live chat intent routing.`))return;try{render(await api("regex/rules",{method:"POST",body:JSON.stringify({operation,revision:state.revision,confirmed:true,rule})}));byId("regex-editor").hidden=true}catch(problem){byId("regex-status").textContent=problem.message}}
  byId("regex-add").addEventListener("click",()=>openEditor());byId("regex-refresh").addEventListener("click",load);byId("regex-cancel").addEventListener("click",()=>{byId("regex-editor").hidden=true});
  byId("regex-editor").addEventListener("submit",event=>{event.preventDefault();if(!byId("regex-confirm").checked)return;change(editing?"update":"create",rulePayload(),editing?`update ${editing}`:`create ${byId("regex-id").value}`)});
  byId("regex-preview").addEventListener("submit",async event=>{event.preventDefault();try{const result=await api("regex/preview",{method:"POST",body:JSON.stringify({phrase:byId("regex-preview-phrase").value,language:byId("regex-preview-language").value})});byId("regex-preview-result").textContent=result.matched?`Matched ${result.name} → ${result.intent}`:`No deterministic match → ${result.intent}`}catch(problem){byId("regex-preview-result").textContent=problem.message}});
  document.querySelector('[data-tab="regex"]').addEventListener("click",()=>{if(!loaded)load()});
})();
